#!/bin/bash
# remove_nsys_results.sh
# This script finds and removes NVIDIA Nsight Systems (nsys) result files.

# Directory to clean (default is current directory)
TARGET_DIR="${1:-.}"

echo "Searching for nsys result files in: $TARGET_DIR"

# Extensions commonly generated by nsys
EXTS=("*.qdrep" "*.nsys-rep" "*.sqlite")

for ext in "${EXTS[@]}"; do
    find "$TARGET_DIR" -type f -name "$ext" -print -delete
done

echo "Cleanup complete."